name: Test publish to TestPyPI

on:
  push:
    branches:
      - feat/pip-publish

jobs:
  publish-to-testpypi:
    runs-on: ubuntu-latest
    environment: Publish

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build deps
        run: python -m pip install --upgrade pip build twine

      - name: Build package
        run: python -m build

      - name: Upload to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: python -m twine upload --skip-existing --verbose --repository  testpypi dist/*